version: '3.7'

services:
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./starage.db:/build
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command:
      - ./bot
    networks:
      - net
networks:
  net:
    driver: bridge