version: '3.7'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command:
      - ./bot
    networks:
      - net
networks:
  net:
    driver: bridge